alpha2_codes = {"Afghanistan": "AF", "Albania": "AL", "Algeria": "DZ", "Andorra": "AD", "Angola": "AO",
                "Antigua-and-Barbuda": "AG", "Argentina": "AR", "Armenia": "AM", "Aruba": "AW", "Australia": "AU",
                "Austria": "AT", "Azerbaijan": "AZ", "Bahamas": "BS", "Bahrain": "BH", "Bangladesh": "BD",
                "Barbados": "BB", "Belarus": "BY", "Belgium": "BE", "Benin": "BJ", "Bermuda": "BM", "Bhutan": "BT",
                "Bolivia": "BO", "Bosnia-and-Herzegovina": "BA", "Brazil": "BR", "Brunei": "BN", "Bulgaria": "BG",
                "Burkina-Faso": "BF", "Cabo-Verde": "CV", "Cambodia": "KH", "Cameroon": "CM", "Canada": "CA",
                "CAR": "CF", "Cayman-Islands": "KY", "Chad": "TD", "Chile": "CL", "China": "CN", "Congo": "CD",
                "Costa-Rica": "CR", "Croatia": "HR", "Cuba": "CU", "Cura": "CW", "Cyprus": "CY", "Czechia": "CZ",
                "Denmark": "DK", "Dominica": "DM", "Dominican-Republic": "DO", "Ecuador": "EC", "Egypt": "EG",
                "El-Salvador": "SV", "Equatorial-Guinea": "GO", "Eritrea": "ER", "Estonia": "EE", "Eswatini": "SZ",
                "Ethiopia": "ET", "Faeroe-Islands": "FO", "Falkland-Islands": "FK", "Fiji": "FJ", "Finland": "FI",
                "France": "FR", "French-Guiana": "GF", "French-Polynesia": "PF", "Gabon": "GA", "Gambia": "GM",
                "Georgia": "GE", "Germany": "DE", "Ghana": "GH", "Gibraltar": "GI", "Greece": "GR", "Grenada": "GD",
                "Greenland": "GL", "Guadeloupe": "GP", "Guam": "GU", "Guatemala": "GT", "Guinea": "GN",
                "Guinea-Bissau": "GW", "Guyana": "GY", "Haiti": "HT", "Honduras": "HN", "Hong-Kong": "HK",
                "Hungary": "HU", "Iceland": "IS", "India": "IN", "Indonesia": "ID", "Iran": "IR", "Iraq": "IQ",
                "Ireland": "IE", "Isle-of-Man": "IM", "Israel": "IL", "Italy": "IT", "Jamaica": "JM", "Japan": "JP",
                "Jordan": "JO", "Kazakhstan": "KZ", "Kenya": "KE", "Kuwait": "KW", "Kyrgyzstan": "KG", "Latvia": "LV",
                "Lebanon": "LB", "Liberia": "LR", "Liechtenstein": "LI", "Lithuania": "LT", "Luxembourg": "LU",
                "Macao": "MO", "Madagascar": "MG", "Malaysia": "MY", "Maldives": "MV", "Mali": "ML", "Malta": "MT",
                "Marshall-Islands": "MH", "Martinique": "MQ", "Mauritania": "MR", "Mauritius": "MU", "Mayotte": "YT",
                "Mexico": "MX", "Moldova": "MD", "Monaco": "MC", "Mongolia": "MN", "Montenegro": "ME",
                "Montserrat": "MS", "Morocco": "MA", "Mozambique": "MZ", "Myanmar": "MM", "Namibia": "NA",
                "Nepal": "NP", "Netherlands": "NL", "New-Caledonia": "NC", "New-Zealand": "NZ", "Nicaragua": "NI",
                "Niger": "NE", "Nigeria": "NG", "Niue": "NU", "Norway": "NO", "Oman": "OM", "Pakistan": "PK",
                "Palau": "PW", "Palestine": "PS", "Panama": "PA", "Papua-New-Guinea": "PG", "Paraguay": "PY",
                "Peru": "PE", "Philippines": "PH", "Poland": "PL", "Portugal": "PT", "Puerto-Rico": "PR", "Qatar": "QA",
                "Romania": "RO", "Russia": "RU", "Rwanda": "RW", "S-Korea": "KR", "Saint-Lucia": "LC",
                "Saint-Martin": "MF", "San-Marino": "SM", "Saudi-Arabia": "SA", "Senegal": "SN", "Serbia": "RS",
                "Seychelles": "SC", "Singapore": "SG", "Sint-Maarten": "SX", "Slovakia": "SK", "Slovenia": "SI",
                "Somalia": "SO", "South-Africa": "ZA", "South-Sudan": "SS", "Spain": "ES", "Sri-Lanka": "LK",
                "St-Barth": "BL", "St-Vincent-Grenadines": "VC", "Sudan": "SD", "Suriname": "SR", "Sweden": "SE",
                "Switzerland": "CH", "Taiwan": "TW", "Tanzania": "TZ", "Thailand": "TH", "Timor-Leste": "TL",
                "Togo": "TG", "Trinidad-and-Tobago": "TT", "Tunisia": "TN", "Turkey": "TR", "US-Virgin-Islands": "VI",
                "British-Virgin-Islands": "VG", "UAE": "AE", "Uganda": "UG", "Ukraine": "UA", "Uruguay": "UY",
                "USA": "US", "Uzbekistan": "UZ", "Venezuela": "VE", "Vietnam": "VN", "Zambia": "ZM", "Zimbabwe": "ZW"
                }
